Feature/7 Criar funcionalidade para cadastro do cliente
desenvolvendo-me/coolify pull request #11
Opened 2024-01-17 16:22 UTC by cassiosantana

Ref #7

2024-01-19 11:10 UTC, PhilipeeX commented on app/views/manager/clients/index.html.erb
Removeu o campo de pesquisa(gem ransack) do index?

2024-01-19 17:24 UTC, marcodotcastro requested changes
- [ ] Está faltando o menu
- [ ] Pesquisar
- [ ] Paginação
- [ ] Filtrar (vazio)
- [ ] Ações (vazio)


O épico goals para ser usado com referencia, ou seja todas as funcionalidades são básicas para os CRUDs

2024-01-23 11:21 UTC, cassiosantana commented on app/views/manager/clients/index.html.erb
Resolvido.

2024-01-25 22:33 UTC, PhilipeeX approved these changes

2024-01-26 13:14 UTC, merged