Feature/6 funcionalidade cadastrar equipamento
desenvolvendo-me/coolify pull request #12
Opened 2024-01-18 13:10 UTC by PhilipeeX

2024-01-18 13:41 UTC, marcodotcastro requested changes
Adicione os testes de features

2024-01-19 11:16 UTC, PhilipeeX commented on spec/features/manager/equipments_feature_spec.rb
Teste de feature criado

2024-01-19 17:19 UTC, marcodotcastro requested changes
- [x] Está faltando o menu de equipamentos

2024-01-20 17:39 UTC, PhilipeeX commented
> * [x]  Está faltando o menu de equipamentos

Menu adicionado

2024-01-22 18:47 UTC, marcodotcastro approved these changes

2024-01-22 19:58 UTC, merged